INSERT INTO employee(empName, empDept, empSalary) VALUES ('Gurgaon', 'DEV_ops', 10000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Rambo', 'DEV_ops', 20000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Mechel', 'Testing', 45000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Dries', 'Integration', 33000);
INSERT INTO employee(empName, empDept, empSalary)VALUES ('Jack', 'Integration', 33000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Ramzy', 'IT', 50000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Mukul', 'IT', 25000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Suraj', 'FN', 15000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Gurgaon', 'DEV_ops', 10000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Rambo', 'DEV_ops', 20000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Mechel', 'Testing', 45000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Dries', 'Integration', 33000);
INSERT INTO employee(empName, empDept, empSalary)VALUES ('Jack', 'Integration', 33000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Ramzy', 'IT', 50000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Mukul', 'IT', 25000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Suraj', 'FN', 15000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Gurgaon', 'DEV_ops', 10000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Rambo', 'DEV_ops', 20000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Mechel', 'Testing', 45000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Dries', 'Integration', 33000);
INSERT INTO employee(empName, empDept, empSalary)VALUES ('Jack', 'Integration', 33000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Ramzy', 'IT', 50000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Mukul', 'IT', 25000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Suraj', 'FN', 15000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Gurgaon', 'DEV_ops', 10000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Rambo', 'DEV_ops', 20000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Mechel', 'Testing', 45000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Dries', 'Integration', 33000);
INSERT INTO employee(empName, empDept, empSalary)VALUES ('Jack', 'Integration', 33000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Ramzy', 'IT', 50000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Mukul', 'IT', 25000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Suraj', 'FN', 15000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Gurgaon', 'DEV_ops', 10000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Rambo', 'DEV_ops', 20000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Mechel', 'Testing', 45000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Dries', 'Integration', 33000);
INSERT INTO employee(empName, empDept, empSalary)VALUES ('Jack', 'Integration', 33000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Ramzy', 'IT', 50000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Mukul', 'IT', 25000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Suraj', 'FN', 15000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Gurgaon', 'DEV_ops', 10000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Rambo', 'DEV_ops', 20000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Mechel', 'Testing', 45000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Dries', 'Integration', 33000);
INSERT INTO employee(empName, empDept, empSalary)VALUES ('Jack', 'Integration', 33000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Ramzy', 'IT', 50000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Mukul', 'IT', 25000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Suraj', 'FN', 15000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Gurgaon', 'DEV_ops', 10000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Rambo', 'DEV_ops', 20000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Mechel', 'Testing', 45000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Dries', 'Integration', 33000);
INSERT INTO employee(empName, empDept, empSalary)VALUES ('Jack', 'Integration', 33000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Ramzy', 'IT', 50000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Mukul', 'IT', 25000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Suraj', 'FN', 15000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Gurgaon', 'DEV_ops', 10000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Rambo', 'DEV_ops', 20000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Mechel', 'Testing', 45000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Dries', 'Integration', 33000);
INSERT INTO employee(empName, empDept, empSalary)VALUES ('Jack', 'Integration', 33000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Ramzy', 'IT', 50000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Mukul', 'IT', 25000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Suraj', 'FN', 15000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Gurgaon', 'DEV_ops', 10000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Rambo', 'DEV_ops', 20000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Mechel', 'Testing', 45000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Dries', 'Integration', 33000);
INSERT INTO employee(empName, empDept, empSalary)VALUES ('Jack', 'Integration', 33000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Ramzy', 'IT', 50000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Mukul', 'IT', 25000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Suraj', 'FN', 15000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Gurgaon', 'DEV_ops', 10000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Rambo', 'DEV_ops', 20000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Mechel', 'Testing', 45000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Dries', 'Integration', 33000);
INSERT INTO employee(empName, empDept, empSalary)VALUES ('Jack', 'Integration', 33000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Ramzy', 'IT', 50000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Mukul', 'IT', 25000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Suraj', 'FN', 15000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Gurgaon', 'DEV_ops', 10000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Rambo', 'DEV_ops', 20000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Mechel', 'Testing', 45000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Dries', 'Integration', 33000);
INSERT INTO employee(empName, empDept, empSalary)VALUES ('Jack', 'Integration', 33000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Ramzy', 'IT', 50000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Mukul', 'IT', 25000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Suraj', 'FN', 15000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Gurgaon', 'DEV_ops', 10000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Rambo', 'DEV_ops', 20000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Mechel', 'Testing', 45000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Dries', 'Integration', 33000);
INSERT INTO employee(empName, empDept, empSalary)VALUES ('Jack', 'Integration', 33000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Ramzy', 'IT', 50000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Mukul', 'IT', 25000);
INSERT INTO employee(empName, empDept, empSalary) VALUES ('Suraj', 'FN', 15000);