DROP TABLE IF EXISTS employee;  
CREATE TABLE employee (  
employeeId INT AUTO_INCREMENT  PRIMARY KEY,  
firstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
employeeDept VARCHAR(50) NOT NULL
); 